Activity 1.1
Remember when we were projecting the iris dataset onto two dimensions and using a clustering/classification algorithm there? Compare (or compute!) those results with the same chosen algorithm used after reducing the dataset to 2 dimensions using PCA instead of just two of the features.

In [94]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.decomposition import FactorAnalysis
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import NearestCentroid
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.metrics import f1_score

In [95]:
#Import our dataset
iris = load_iris()
X = iris.data
Y = iris.target
data1 = pd.read_csv("iris.csv")

In [96]:
print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [97]:
feature_names =data1.columns[0:4]
print(feature_names)

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width'], dtype='object')


First we do Factor Analysis

In [98]:
factor = FactorAnalysis(n_components=4).fit(X) #Components set to 4, which will appear as rows below

In [126]:
#Apply the PCA fitting algorithm
pca = PCA().fit(X)

#Print the output, Explained variance by each component, npte using word components

print('Explained variance by each component: %s' % pca.explained_variance_ratio_)
print('\n')
print(pd.DataFrame(pca.components_,columns=feature_names))

Explained variance by each component: [0.92461872 0.05306648 0.01710261 0.00521218]


   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0      0.361387    -0.084523      0.856671     0.358289
1      0.656589     0.730161     -0.173373    -0.075481
2     -0.582030     0.597911      0.076236     0.545831
3     -0.315487     0.319723      0.479839    -0.753657


Now Reun using 2 components

In [128]:
New_X =iris.data[:,0:3]

In [129]:
feature_names = data1.columns[0:3]

In [130]:
print(New_X[:5])

[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]


In [131]:
factor = FactorAnalysis(n_components=3).fit(New_X) #Components set to 3, which will appear as rows below

In [132]:
#Apply the PCA fitting algorithm
pca = PCA().fit(New_X)

#Print the output, Explained variance by each component, npte using word components

print('Explained variance by each component: %s' % pca.explained_variance_ratio_)
print('\n')
print(pd.DataFrame(pca.components_,columns=feature_names))

Explained variance by each component: [0.92464061 0.06046599 0.0148934 ]


   Sepal.Length  Sepal.Width  Petal.Length
0      0.389833    -0.091008      0.916377
1      0.639223     0.743059     -0.198135
2     -0.662890     0.663009      0.347844


In [125]:
New2_X =iris.data[:,(0,2)]
#New2_X =iris.data[:,0:3]

In [106]:
print(New2_X[:5])

[[5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]]


In [107]:
feature_names = ['Sepal.Length','Petal.Length']

In [108]:
factor = FactorAnalysis(n_components=3).fit(New2_X) #Components set to 3, which will appear as rows below

In [109]:
#Apply the PCA fitting algorithm
pca = PCA().fit(New2_X)

#Print the output, Explained variance by each component, npte using word components

print('Explained variance by each component: %s' % pca.explained_variance_ratio_)
print('\n')
print(pd.DataFrame(pca.components_,columns=feature_names))

Explained variance by each component: [0.9631579 0.0368421]


   Sepal.Length  Petal.Length
0      0.393606      0.919279
1     -0.919279      0.393606


In [110]:
 X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)


In [116]:
model = neighbors.KNeighborsClassifier(n_neighbors=15)
model.fit(X_train,Y_train)
y_predict = model.predict(X_test)

f1_score(Y_test,y_predict, average='macro')

1.0

In [117]:
New2_X_train, New2_X_test, New2_Y_train, New2_Y_test = train_test_split(New2_X, Y, test_size=0.2, random_state=0)
#print(New2_X_train,New2_Y_train)

In [115]:
model2 = neighbors.KNeighborsClassifier(n_neighbors=15)
model2.fit(New2_X_train,New2_Y_train)

y_predict2 = model2.predict(New2_X_test)


f1_score(New2_Y_test,y_predict2, average='macro')



0.957351290684624

What I think we are to say here is, PCA returns a score of 99% using the two choosen columns, it its also comfirms by running the same classifier on all columns of the Iris data, and using the first col and third column that we can get the same result just using two columns, so a good reduction. Using 4 and three components did not change much compared to using two